import type { Metadata } from "next";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
} from "@clerk/nextjs";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { Play } from "next/font/google";

const play = Play({
  weight: ["400", "700"],
  fallback: ["Roboto", "Roboto Condensed"],
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en" className={play.className}>
        <body className="h-[calc(60vh)] bg-gray-800">
          <SignedOut>
            <SignInButton>
              <Button>Nevtreh</Button>
            </SignInButton>
          </SignedOut>
          <SignedIn>{children}</SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}

// __Play_976028", "__Play_Fallback_976028
